function reportText = formatReportText(result)
% FORMATREPORTTEXT  Convert a predictWithThreshold() result struct into
% clinician-readable report text.
%
%   reportText = formatReportText(result)
%
%   INPUT:
%     result - the struct returned by predictWithThreshold.m, containing
%              at minimum: predictedGrade, confidence, referableProb,
%              isReferable
%
%   OUTPUT:
%     reportText - struct of strings, ready to drop into a report layout:
%       .icdrLevel       - e.g. "ICDR Grade 4 (Proliferative DR)"
%       .confidenceBand  - "High" / "Moderate" / "Low"
%       .confidenceNote  - one sentence framing what the confidence means
%       .referralLine    - the recommendation sentence
%       .disclaimer      - fixed safety/scope disclaimer, always included
%       .summary         - single paragraph combining the above, for a
%                          quick-read version of the report

grade = string(result.predictedGrade);

% ---- Map class name to ICDR level + full name ----
% ICDR (International Clinical Diabetic Retinopathy) scale, 0-4.
icdrMap = containers.Map(...
    {'No_DR', 'Mild', 'Moderate', 'Severe', 'Proliferate_DR'}, ...
    {'ICDR Grade 0 (No apparent retinopathy)', ...
    'ICDR Grade 1 (Mild nonproliferative DR)', ...
    'ICDR Grade 2 (Moderate nonproliferative DR)', ...
    'ICDR Grade 3 (Severe nonproliferative DR)', ...
    'ICDR Grade 4 (Proliferative DR)'});

if isKey(icdrMap, grade)
    reportText.icdrLevel = icdrMap(grade);
else
    reportText.icdrLevel = sprintf('Unrecognized grade: %s', grade);
end

% ---- Confidence banding ----
% Bands chosen to be conservative for a screening tool: only truly
% high scores get called "High", and the note explicitly reminds the
% reader that a lower band does NOT mean the referral decision is
% less trustworthy -- the threshold-based referable decision is
% separate from and more robust than the raw top-class confidence.
conf = result.confidence;
if conf >= 0.90
    reportText.confidenceBand = "High";
    reportText.confidenceNote = sprintf(...
        "The model's predicted grade carries high confidence (%.1f%%).", ...
        conf*100);
elseif conf >= 0.70
    reportText.confidenceBand = "Moderate";
    reportText.confidenceNote = sprintf(...
        "The model's predicted grade carries moderate confidence (%.1f%%). " + ...
        "The image may show features consistent with more than one grade.", ...
        conf*100);
else
    reportText.confidenceBand = "Low";
    reportText.confidenceNote = sprintf(...
        "The model's predicted grade carries low confidence (%.1f%%). " + ...
        "This case may sit near a grading boundary; clinical correlation " + ...
        "is recommended regardless of the referral decision below.", ...
        conf*100);
end

% ---- Referral recommendation ----
% This is intentionally driven by isReferable / referableProb, NOT by
% confidenceBand -- the tuned threshold decision is the clinically
% validated one (sensitivity 92.4% at this threshold per Stage 3
% results), and stays authoritative even when top-class confidence
% is low. See note in confidenceNote above.
if result.isReferable
    reportText.referralLine = sprintf(...
        "RECOMMENDATION: Refer for ophthalmological evaluation. " + ...
        "Referable-DR probability: %.1f%% (decision threshold: %.0f%%).", ...
        result.referableProb*100, 0.2*100);
else
    reportText.referralLine = sprintf(...
        "RECOMMENDATION: Routine screening interval; no urgent referral " + ...
        "indicated at this time. Referable-DR probability: %.1f%% " + ...
        "(decision threshold: %.0f%%).", ...
        result.referableProb*100, 0.2*100);
end

% ---- Fixed disclaimer, always included ----
reportText.disclaimer = "This output is generated by an automated " + ...
    "screening aid and does not constitute a medical diagnosis. " + ...
    "All findings should be confirmed by a qualified eye care " + ...
    "professional before any clinical decision is made.";

% ---- One-paragraph summary ----
reportText.summary = sprintf(...
    "%s\n%s\n%s\n\n%s", ...
    reportText.icdrLevel, ...
    reportText.confidenceNote, ...
    reportText.referralLine, ...
    reportText.disclaimer);

end