function R = enhancementExperiment()
% ENHANCEMENTEXPERIMENT  Does enhancing a borderline photograph (enhanceForReview) help the deployed Stage 3 model? Measured, not assumed.
%
%   R = enhancementExperiment()      writes validation/results/enhancement.md
%
% 150 held-out APTOS test photographs (30 per grade, fixed seed), full resolution. Each is degraded the way validation/QUALITY.md
% degraded photos (darken, blur, noise; blur and noise scaled to the photo's size), then graded twice: as is, and after
% enhanceForReview. Referral AUC, sensitivity and specificity at the deployed threshold. "Borderline" means what the Stage 1 gate
% accepts with a warning or rejects.
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root, 'utils'), fullfile(root, 'stage1_quality'), fullfile(root, 'stage_3'));
    [net, thr] = loadStage3Model();
    classes = cellstr(net.Layers(end).Classes);
    refCols = ismember(classes, {'Moderate', 'Severe', 'Proliferate_DR'});
    sz = net.Layers(1).InputSize(1:2);

    S = readtable(fullfile(root, 'validation', 'results', 'splits.csv'), 'TextType', 'char');
    S = S(strcmp(S.split, 'test'), :);
    grades = {'No_DR', 'Mild', 'Moderate', 'Severe', 'Proliferate_DR'};
    rng(11); pick = [];
    for g = 1:numel(grades)
        idx = find(strcmp(S.label, grades{g}));
        pick = [pick; idx(randperm(numel(idx), min(30, numel(idx))))]; %#ok<AGROW>
    end
    S = S(pick, :);
    truth = ismember(S.label, {'Moderate', 'Severe', 'Proliferate_DR'});
    conds = {'clean', @(x) x; 'darken x0.5', @(x) uint8(double(x) * 0.5); 'darken x0.35', @(x) uint8(double(x) * 0.35); ...
             'blur (1 px at 224)', @(x) imgaussfilt(x, size(x, 2) / 224); 'noise (sd 10)', @(x) uint8(double(x) + 10 * randn(size(x)))};

    n = height(S); C = size(conds, 1);
    score = nan(n, C, 2);
    for i = 1:n
        img = imread(fullfile(root, 'data', 'aptos2019_full', 'train_images', [S.id{i} '.png']));
        for c = 1:C
            rng(i);
            d = conds{c, 2}(img);
            e = enhanceForReview(d);
            batch = cat(4, preprocessStage3Input(d, sz), preprocessStage3Input(e, sz));
            [~, p] = stage3Scores(net, batch);
            score(i, c, :) = sum(p(:, refCols), 2);
        end
        if mod(i, 25) == 0, fprintf('  %d/%d\n', i, n); end
    end

    lines = {'# Does enhancement help the grading network? (Stage 1, enhanceForReview.m)', '', ...
        sprintf(['Generated by `stage1_quality/enhancementExperiment.m`. %d held-out APTOS test photographs (30 per grade), full resolution, deployed Stage 3 ' ...
        'model at its threshold %.3g. Each photograph is degraded, then graded as is and after `enhanceForReview` (illumination normalisation, CLAHE, ' ...
        'bilateral denoising).'], n, thr), '', ...
        '| Condition | AUC as is | AUC enhanced | Sens / spec as is | Sens / spec enhanced |', '|---|---|---|---|---|'};
    for c = 1:C
        a0 = rocAuc(score(:, c, 1), truth); a1 = rocAuc(score(:, c, 2), truth);
        [s0, p0] = rates(score(:, c, 1) >= thr, truth); [s1, p1] = rates(score(:, c, 2) >= thr, truth);
        R.(matlab.lang.makeValidName(conds{c, 1})) = struct('auc', [a0 a1], 'sens', [s0 s1], 'spec', [p0 p1]);
        lines{end + 1} = sprintf('| %s | %.3f | %.3f | %.1f%% / %.1f%% | %.1f%% / %.1f%% |', conds{c, 1}, a0, a1, 100 * s0, 100 * p0, 100 * s1, 100 * p1); %#ok<AGROW>
    end
    lines = [lines, {'', ['Specificity here is lower than in REPORT.md because the sample is enriched: 30 photographs per grade, so Mild eyes make up ' ...
        'half of the non-referable group. Compare the columns, not these numbers with REPORT.md.'], '', ['If "enhanced" is not clearly better, the app is right to grade the unprocessed photograph and to use the enhanced copy only ' ...
        'for display. The network was trained on unprocessed photographs, so enhancement shifts its inputs away from what it learned.']}];
    fid = fopen(fullfile(root, 'validation', 'results', 'enhancement.md'), 'w'); fprintf(fid, '%s\n', lines{:}); fclose(fid);
    fprintf('%s\n', lines{:});
end

function [sens, spec] = rates(flag, truth)
    sens = mean(flag(truth)); spec = mean(~flag(~truth));
end

function a = rocAuc(score, label)
    pos = score(label); neg = score(~label);
    r = tiedrank([pos; neg]);
    a = (sum(r(1:numel(pos))) - numel(pos) * (numel(pos) + 1) / 2) / (numel(pos) * numel(neg));
end
