"""Judge the Stage 4 heatmaps (needs results/gradcam_aptos.mat and results/gradcam_idrid_seg.mat from gradcam_eval.py).

Three separate questions, because one test alone can mislead:
  1. Sanity check (model randomisation): does the map change when the network's weights are randomised? If not, it shows the image, not the model.
  2. Deletion: replacing the cells the map calls most important with the retina's mean colour should lower the referral score more than replacing the same
     number of random cells, and least for the coldest cells. (An earlier version blanked cells with black; the black patches themselves raised the score, so it proved nothing.)
  3. Localisation: on IDRiD photographs with expert lesion masks, is the map hotter on lesions than elsewhere?

    python validation/analyze_gradcam.py        # writes results/gradcam.md
"""
from pathlib import Path

import cv2
import numpy as np
from scipy.io import loadmat

HERE = Path(__file__).resolve().parent
RES = HERE / "results"
SEGROOT = HERE.parent / "data" / "idrid_segmentation" / "A. Segmentation" / "A. Segmentation" / "2. All Segmentation Groundtruths"
KS = (4, 8, 12)


def load(name):
    d = loadmat(RES / f"gradcam_{name}.mat", squeeze_me=True)
    return {k: v for k, v in d.items() if not k.startswith("__")}


def corr(a, b, mask):
    x, y = a[mask], b[mask]
    if x.std() < 1e-9 or y.std() < 1e-9:
        return np.nan
    return float(np.corrcoef(x, y)[0, 1])


def spearman(a, b, mask):
    x, y = a[mask], b[mask]
    if x.std() < 1e-9 or y.std() < 1e-9:
        return np.nan
    rx, ry = np.argsort(np.argsort(x)), np.argsort(np.argsort(y))
    return float(np.corrcoef(rx, ry)[0, 1])


def auc(score, positive):
    pos, neg = score[positive], score[~positive]
    if len(pos) == 0 or len(neg) == 0:
        return np.nan
    order = np.argsort(np.concatenate([pos, neg]), kind="mergesort")
    ranks = np.empty(len(order))
    combined = np.concatenate([pos, neg])[order]
    i = 0
    while i < len(combined):
        j = i
        while j + 1 < len(combined) and combined[j + 1] == combined[i]:
            j += 1
        ranks[order[i:j + 1]] = (i + j) / 2 + 1
        i = j + 1
    return float((ranks[:len(pos)].sum() - len(pos) * (len(pos) + 1) / 2) / (len(pos) * len(neg)))


def bootstrap_ci(x, repeats=2000, seed=0):
    rng = np.random.default_rng(seed)
    x = np.asarray(x)
    means = [x[rng.integers(0, len(x), len(x))].mean() for _ in range(repeats)]
    return np.percentile(means, [2.5, 97.5])


def lesion_mask_224(stem, split, bbox, origsize):
    """Union of the expert lesion masks (microaneurysms, haemorrhages, exudates), and the optic disc mask, mapped into the model's 224x224 view."""
    x, y, w, h = [int(v) for v in bbox]
    H, W = [int(v) for v in origsize]
    folder = "a. Training Set" if split == "train" else "b. Testing Set"
    out = {}
    for name, sub, code in (("lesion", ("1. Microaneurysms", "2. Haemorrhages", "3. Hard Exudates", "4. Soft Exudates"), ("MA", "HE", "EX", "SE")), ("disc", ("5. Optic Disc",), ("OD",))):
        full = np.zeros((H, W), bool)
        for s, c in zip(sub, code):
            f = SEGROOT / folder / s / f"{stem}_{c}.tif"
            if f.exists():
                m = cv2.imread(str(f), cv2.IMREAD_GRAYSCALE)
                if m is not None:
                    full |= m > 0
        crop = full[y - 1:y - 1 + h, x - 1:x - 1 + w]                   # MATLAB boxes are 1-based
        ch, cw = crop.shape
        if ch > cw:
            pad = ch - cw
            crop = np.pad(crop, ((0, 0), (pad // 2, pad - pad // 2)))
        elif cw > ch:
            pad = cw - ch
            crop = np.pad(crop, ((pad // 2, pad - pad // 2), (0, 0)))
        out[name] = cv2.resize(crop.astype(np.uint8), (224, 224), interpolation=cv2.INTER_NEAREST).astype(bool)
    return out


def main():
    a = load("aptos")
    n = len(a["refprob"])
    fov = a["fov"].astype(bool)
    L = ["# Stage 4: can the heatmaps be trusted?", "",
         "Generated by `validation/analyze_gradcam.py` from `validation/gradcam_eval.py` (MATLAB). The map is a Grad-CAM of the **referral score** "
         "(P(Moderate)+P(Severe)+P(Proliferate_DR)), computed on the same cropped image that is graded, on a 7x7 grid (each cell is 32 px of the 224 px view).", ""]

    # --- 0. what the old explanation did (all 548 held-out test photographs, deployed pipeline)
    import csv
    classes = ["Mild", "Moderate", "No_DR", "Proliferate_DR", "Severe"]
    rows = list(csv.DictReader(open(RES / "app_test_cropmirror.csv", encoding="utf-8")))
    n_test = len(rows)
    probs = np.array([[float(r[f"p_{c}"]) for c in classes] for r in rows])
    referral = probs[:, [1, 3, 4]].sum(1)
    top = np.array(classes)[probs.argmax(1)]
    flagged_all = referral >= 0.20
    mismatch = flagged_all & np.isin(top, ["No_DR", "Mild"])
    L += ["## 0. Why the map was changed", "",
          "The referral decision uses the summed referral probability, but the earlier heatmap explained the single most likely *class*. "
          f"Of the {int(flagged_all.sum())} of {len(rows)} held-out test eyes that the threshold flags for referral, the most likely class was No_DR or Mild for "
          f"**{int(mismatch.sum())} ({mismatch.sum() / flagged_all.sum() * 100:.0f}%)**: for those eyes the old map explained a grade that did not drive the decision. "
          "The map now explains the referral score itself.", ""]

    # --- 1. randomisation
    key = {}
    L += ["## 1. Sanity check: randomise the network's weights", "",
          "Correlation (inside the retina) between the real map and the map from a network with random weights. A trustworthy explanation should look "
          "**different** (correlation near 0). Median of the absolute values, over eyes where both maps are non-empty.", "",
          "| Randomised part | Pearson (median abs) | Spearman (median abs) | Eyes compared |", "|---|---|---|---|"]
    for label, cols in (("Classifier layer only (2 seeds)", (0, 1)), ("Every layer (2 seeds)", (2, 3))):
        pe, sp = [], []
        for i in range(n):
            for c in cols:
                m = fov[i]
                pe.append(corr(a["referral"][i], a["rand"][i, c], m))
                sp.append(spearman(a["referral"][i], a["rand"][i, c], m))
        pe, sp = np.array(pe), np.array(sp)
        key[label] = float(np.nanmedian(np.abs(pe)))
        L.append(f"| {label} | {np.nanmedian(np.abs(pe)):.2f} | {np.nanmedian(np.abs(sp)):.2f} | {int(np.sum(~np.isnan(pe)))} of {2 * n} |")
    L.append("")

    # --- 2. deletion
    L += ["## 2. Deletion with a neutral fill", "",
          "Cells of the 7x7 grid inside the retina are replaced by the retina's mean colour; the table is the fall in the referral score "
          "(positive = the score dropped), averaged over eyes the model clearly flags (referral score >= 0.5). A faithful map: hottest > random > coldest.", "",
          "| Cells replaced | Hottest | Random (average of 20 draws) | Coldest | Hottest minus random (95% interval) | Eyes where hottest > random |", "|---|---|---|---|---|---|"]
    sel = a["refprob"] >= 0.5
    for j, k in enumerate(KS):
        hot, rnd, cold = a["drop_hot"][sel, j], a["drop_random"][sel, j], a["drop_cold"][sel, j]
        lo, hi = bootstrap_ci(hot - rnd)
        key[f"del{k}"] = (float(hot.mean()), float(rnd.mean()), float(np.mean(hot - rnd)), float(lo), float(hi), float(np.mean(hot > rnd)))
        L.append(f"| {k} of about 38 | {hot.mean():.3f} | {rnd.mean():.3f} | {cold.mean():.3f} | {np.mean(hot - rnd):+.3f} ({lo:+.3f} to {hi:+.3f}) | {np.mean(hot > rnd) * 100:.0f}% ({int(sel.sum())} eyes) |")
    L.append("")

    # --- 3. localisation on lesion-annotated IDRiD photographs
    s = load("idrid_seg")
    m = len(s["refprob"])
    rows = []
    for i in range(m):
        stem = Path(str(s["paths"][i])).stem
        masks = lesion_mask_224(stem, str(s["labels"][i]), s["bbox"][i], s["origsize"][i])
        f = s["fov"][i].astype(bool)
        les = masks["lesion"] & f
        if les.sum() < 30:
            continue
        rows.append((i, f, les, masks["disc"] & f))
    L += ["## 3. Localisation on IDRiD photographs with expert lesion masks", "",
          f"{len(rows)} of {m} photographs have lesion masks (microaneurysms, haemorrhages, exudates). Pixel-level agreement between the map and the masks, inside the retina. "
          "AUC 0.5 is chance. 'Chance' columns are what a randomly placed hottest pixel would score (the share of the retina that is lesion, or within 16 px of a lesion).", "",
          "| Map | Pixel AUC (median over photographs) | Hottest pixel on a lesion (chance) | Hottest pixel within 16 px of a lesion (chance) | Mean heat on lesions / elsewhere |", "|---|---|---|---|---|"]

    def summarise(maps, name):
        aucs, hit, near, chance, chance_near, ratio = [], [], [], [], [], []
        for i, f, les, disc in rows:
            h = maps(i)
            if h.max() <= 0:
                continue
            aucs.append(auc(h[f], les[f]))
            y, x = np.unravel_index(int(np.argmax(np.where(f, h, -1))), h.shape)
            hit.append(bool(les[y, x]))
            grown = cv2.dilate(les.astype(np.uint8), np.ones((33, 33), np.uint8)).astype(bool)
            near.append(bool(grown[y, x]))
            chance.append(les.sum() / f.sum())
            chance_near.append((grown & f).sum() / f.sum())
            ratio.append(h[les].mean() / max(h[f & ~les].mean(), 1e-9))
        key[name] = (float(np.nanmedian(aucs)), float(np.mean(hit)), float(np.mean(chance)))
        L.append(f"| {name} | {np.nanmedian(aucs):.3f} | {np.mean(hit) * 100:.0f}% ({np.mean(chance) * 100:.1f}%) | {np.mean(near) * 100:.0f}% ({np.mean(chance_near) * 100:.0f}%) | {np.median(ratio):.2f} |")
        return aucs

    summarise(lambda i: s["referral"][i], "Referral map (used by the app)")
    summarise(lambda i: s["argmax"][i], "Most-likely-class map (the earlier one)")
    summarise(lambda i: s["rand"][i, 2], "Randomised network (every layer), for comparison")
    L.append("")

    # disc attraction
    share_disc, area_disc = [], []
    for i, f, les, disc in rows:
        h = s["referral"][i]
        if h.sum() > 0 and disc.sum() > 0:
            share_disc.append(h[disc].sum() / h[f].sum())
            area_disc.append(disc.sum() / f.sum())
    ratio_disc = np.median(share_disc) / np.median(area_disc)
    L += [f"Optic disc: the disc carries {np.median(share_disc) * 100:.0f}% of the referral-map heat (median) while covering {np.median(area_disc) * 100:.0f}% of the retina "
          f"({ratio_disc:.1f}x its share of the area), so the map is {'drawn to' if ratio_disc > 1.5 else 'not specially drawn to'} the disc.", ""]
    ref, old = key["Referral map (used by the app)"], key["Most-likely-class map (the earlier one)"]
    d12 = key["del12"]
    L += ["## Reading of the results", "",
          f"- **The map depends on what the network learned.** With random weights the map correlates only {key['Every layer (2 seeds)']:.2f} (all layers) to {key['Classifier layer only (2 seeds)']:.2f} "
          "(classifier only) with the real one, so it is not just an edge or brightness map of the image.",
          f"- **The hottest cells matter more than other cells, but the effect is modest.** Replacing 12 hottest cells lowers the referral score {d12[2]:+.3f} more than 12 random cells "
          f"(95% interval {d12[3]:+.3f} to {d12[4]:+.3f}; hottest more important in {d12[5] * 100:.0f}% of eyes). In absolute terms removing the hottest cells lowers the score by only {d12[0]:.3f} on average: "
          "the evidence for referral is spread over the retina, so a flagged eye stays flagged. (The fill is itself unnatural: replacing random cells RAISES the score, so only the comparison between rows is meaningful.)",
          f"- **It is hotter on lesions, weakly.** Pixel AUC {ref[0]:.2f} on lesion masks (0.5 is chance); the hottest pixel is on a lesion in {ref[1] * 100:.0f}% of photographs against {ref[2] * 100:.1f}% by chance. "
          "It is far from a lesion detector.",
          f"- **The earlier map was not usable for localisation:** AUC {old[0]:.2f} (chance), hottest pixel on a lesion in {old[1] * 100:.0f}% of photographs. Explaining the referral score fixed that.", ""]
    L += ["## What this does and does not show", "",
          "- The maps are coarse (a 7x7 grid). They show regions, not lesions.",
          "- Passing these tests would show the map reflects what drives the network's score. It would not show the network reasons like a clinician.",
          "- Localisation uses IDRiD photographs only (the only lesion masks available); deletion and randomisation use APTOS test photographs.", ""]
    import json

    (RES / "gradcam.json").write_text(json.dumps({
        "randomised_all_layers_abs_corr": key["Every layer (2 seeds)"], "randomised_classifier_abs_corr": key["Classifier layer only (2 seeds)"],
        "deletion_12_cells": {"hottest_drop": d12[0], "random_drop": d12[1], "hottest_minus_random": d12[2], "ci": [d12[3], d12[4]], "share_of_eyes_hottest_larger": d12[5]},
        "localisation_referral_map": {"pixel_auc": ref[0], "hottest_pixel_on_lesion": ref[1], "chance": ref[2]},
        "localisation_earlier_map": {"pixel_auc": old[0], "hottest_pixel_on_lesion": old[1]},
        "old_map_mismatch": {"flagged": int(flagged_all.sum()), "mismatched": int(mismatch.sum()), "of": n_test},
    }, indent=1), encoding="utf-8")
    text = "\n".join(L)
    (RES / "gradcam.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
