"""Summarise stage3_pipeline_experiment.py.

For each way of preparing the image:
  * the referral threshold is chosen on the APTOS VALIDATION split only (the highest threshold whose validation sensitivity is at least 95%),
  * that threshold is then applied unchanged to the APTOS TEST split and to IDRiD,
  * AUC differences against today's pipeline ('resize') come with paired bootstrap intervals (2,000 resamples of the same images).

    python validation/analyze_stage3_pipeline.py        # writes results/stage3_pipeline.md and .json
"""
import csv
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "calibration"))
import core  # noqa: E402

RES = HERE / "results"
METHODS = ["resize", "crop", "crop_mirror"]
IDRID_EXTRA = ["pad", "cropsquash"]
TARGET_SENS = 0.95


def load(method, name):
    rows = list(csv.DictReader(open(RES / f"s3_{method}_{name}.csv", encoding="utf-8")))
    truth = np.array([r["label"] in core.REFERABLE for r in rows], dtype=bool)
    probs = np.array([[float(r[f"p_{c}"]) for c in core.CLASSES] for r in rows])
    return [r["id"] for r in rows], truth, probs, [r["label"] for r in rows]


def auc(truth, score):
    order = np.argsort(score, kind="mergesort")
    ranks = np.empty(len(score))
    ranks[order] = np.arange(1, len(score) + 1)
    for v in np.unique(score):
        m = score == v
        if m.sum() > 1:
            ranks[m] = ranks[m].mean()
    n1, n0 = truth.sum(), (~truth).sum()
    return (ranks[truth].sum() - n1 * (n1 + 1) / 2) / (n1 * n0)


def paired_auc_difference(truth, score_a, score_b, repeats=2000, seed=0):
    rng = np.random.default_rng(seed)
    n = len(truth)
    diffs = []
    for _ in range(repeats):
        i = rng.integers(0, n, n)
        if truth[i].all() or (~truth[i]).all():
            continue
        diffs.append(auc(truth[i], score_b[i]) - auc(truth[i], score_a[i]))
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    return auc(truth, score_b) - auc(truth, score_a), lo, hi


def choose_threshold(truth, score):
    best = None
    for t in core.GRID:
        r = core.rates(core.confusion(truth, score, t))
        if r["sensitivity"] >= TARGET_SENS:
            best = t
    return best if best is not None else core.DEFAULT_THRESHOLD


def fmt(r, key):
    lo, hi = r[f"{key}_ci"]
    return f"{r[key] * 100:.1f}% ({lo * 100:.1f}-{hi * 100:.1f})"


def main():
    scores, results = {}, {}
    for method in METHODS:
        _, tv, pv, _ = load(method, "aptos_validation")
        _, tt, pt, _ = load(method, "aptos_test")
        _, ti, pi, _ = load(method, "idrid")
        sv, st, si = core.referral_score(pv), core.referral_score(pt), core.referral_score(pi)
        thr = choose_threshold(tv, sv)
        scores[method] = (tt, st, ti, si)
        results[method] = {"threshold": float(thr), "deployed": {}, "chosen": {}}
        for label, t in (("deployed", core.DEFAULT_THRESHOLD), ("chosen", thr)):
            results[method][label] = {
                "aptos_test": core.rates(core.confusion(tt, st, t)), "idrid": core.rates(core.confusion(ti, si, t)),
            }
        results[method]["auc"] = {"aptos_val": auc(tv, sv), "aptos_test": auc(tt, st), "idrid": auc(ti, si)}

    out = ["# Stage 3 input pipeline: what changes when the image is prepared differently", "",
           "Generated by `validation/analyze_stage3_pipeline.py`. The deployed network is unchanged; only how each photo is prepared (and, for `crop_mirror`, "
           "averaging with the mirror image) differs. `resize` is what the app did before this change.", "",
           "Thresholds marked *chosen* are picked on APTOS **validation** only (highest threshold with validation sensitivity >= 95%) and then applied unchanged to APTOS test "
           "and IDRiD. IDRiD was looked at while these methods were being explored, so its numbers are directional, not a clean held-out result.", ""]

    out += ["## Ranking quality (AUC, higher is better)", "", "| Method | APTOS validation | APTOS test | IDRiD |", "|---|---|---|---|"]
    for m in METHODS:
        a = results[m]["auc"]
        out.append(f"| {m} | {a['aptos_val']:.3f} | {a['aptos_test']:.3f} | {a['idrid']:.3f} |")
    out += ["", "AUC difference against `resize` (paired bootstrap, 95% interval; an interval that excludes 0 is a real difference for these images):", "",
            "| Method | APTOS test | IDRiD |", "|---|---|---|"]
    for m in METHODS[1:]:
        tt, st, ti, si = scores[m]
        _, base_st, _, base_si = scores["resize"]
        d1 = paired_auc_difference(tt, base_st, st)
        d2 = paired_auc_difference(ti, base_si, si)
        results[m]["auc_difference"] = {"aptos_test": d1, "idrid": d2}
        out.append(f"| {m} | {d1[0]:+.3f} ({d1[1]:+.3f} to {d1[2]:+.3f}) | {d2[0]:+.3f} ({d2[1]:+.3f} to {d2[2]:+.3f}) |")

    for label, title in (("deployed", "At the threshold the app uses today (0.20)"), ("chosen", "At the threshold chosen on APTOS validation for each method")):
        out += ["", f"## {title}", "", "| Method | Threshold | APTOS test sensitivity | APTOS test specificity | IDRiD sensitivity | IDRiD specificity |", "|---|---|---|---|---|---|"]
        for m in METHODS:
            t = core.DEFAULT_THRESHOLD if label == "deployed" else results[m]["threshold"]
            r = results[m][label]
            out.append(f"| {m} | {t:.2f} | {fmt(r['aptos_test'], 'sensitivity')} | {fmt(r['aptos_test'], 'specificity')} | {fmt(r['idrid'], 'sensitivity')} | {fmt(r['idrid'], 'specificity')} |")

    if all((RES / f"s3_{m}_idrid.csv").exists() for m in IDRID_EXTRA):
        out += ["", "## Why does cropping help on IDRiD? (IDRiD only, 516 photographs, threshold 0.20)", "",
                "| Preparation | What it does | AUC | Sensitivity | Specificity |", "|---|---|---|---|---|"]
        for m, what in (("resize", "whole 3:2 frame squashed to a square"), ("pad", "whole frame padded to a square (no distortion, black borders kept)"),
                        ("cropsquash", "black border cropped, then stretched to a square (distorted)"), ("crop", "black border cropped, padded to a square (no distortion)")):
            _, truth, probs, _ = load(m, "idrid")
            s = core.referral_score(probs)
            r = core.rates(core.confusion(truth, s, core.DEFAULT_THRESHOLD))
            out.append(f"| {m} | {what} | {auc(truth, s):.3f} | {fmt(r, 'sensitivity')} | {fmt(r, 'specificity')} |")

    text = "\n".join(out) + "\n"
    (RES / "stage3_pipeline.md").write_text(text, encoding="utf-8")
    (RES / "stage3_pipeline.json").write_text(json.dumps(results, indent=1, default=float), encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
