"""Stage 1 'is the optic disc in the picture?' check (backend/quality.py, disc_score) against real data.

Three questions, all answered with the code that ships:
  1. Where does the detector put the disc? Compared with the disc centres marked by experts on all 516 IDRiD photographs.
  2. Does its confidence tell a frame that contains the disc from one that does not? Test frames are cut from the IDRiD photographs (a random window of 35-70%
     of the photograph's width, only proportions the gate already accepts) and labelled by the expert disc position: the disc fully inside, or clearly outside.
  3. How often does it warn on whole photographs (all 3,662 APTOS and 516 IDRiD)?

    python validation/disc_check.py        # writes results/disc_check.md (about 10 minutes)
"""
import csv
import random
import sys
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "validation" / "results"
APTOS = ROOT / "data" / "aptos2019" / "colored_images"
LOC = ROOT / "data" / "idrid_localization" / "C. Localization" / "C. Localization"
sys.path.insert(0, str(ROOT / "backend"))
import quality  # noqa: E402

THRESHOLD = quality.THRESHOLDS["disc_warn"]


def disc_ground_truth():
    """{(split, name): (x, y, image path)} from the experts' optic disc centre markups."""
    out = {}
    for split, folder, name in (("train", "a. Training Set", "a. IDRiD_OD_Center_Training Set_Markups.csv"),
                                ("test", "b. Testing Set", "b. IDRiD_OD_Center_Testing Set_Markups.csv")):
        for r in csv.reader(open(LOC / "2. Groundtruths" / "1. Optic Disc Center Location" / name, encoding="utf-8-sig")):
            if r and r[0].startswith("IDRiD") and r[1]:
                out[(split, r[0])] = (float(r[1]), float(r[2]), LOC / "1. Original Images" / folder / f"{r[0]}.jpg")
    return out


def auc(pos, neg):
    pos, neg = np.array(pos), np.array(neg)
    return float(np.mean([(p > neg).mean() + 0.5 * (p == neg).mean() for p in pos]))


def main():
    truth = disc_ground_truth()
    keys = sorted(truth)
    rng = random.Random(0)

    # 1. localisation accuracy on whole IDRiD photographs
    err, scores_full_idrid = [], []
    for k in keys:
        x0, y0, path = truth[k]
        img = cv2.imread(str(path))
        h, w = img.shape[:2]
        m = quality.measures(img)
        scores_full_idrid.append(m["disc_score"])
        retina_width = w * 0.70                       # IDRiD retina spans about 70% of the frame width (measured: aspect box)
        err.append(np.hypot(m["disc_x"] * w - x0, m["disc_y"] * h - y0) / retina_width)
    err = np.array(err)

    # 2. frames with / without the disc
    with_disc, without_disc = [], []
    for k in rng.sample(keys, 200):
        x0, y0, path = truth[k]
        img = cv2.imread(str(path))
        h, w = img.shape[:2]
        for _ in range(6):
            cw = int(w * rng.uniform(0.35, 0.7))
            ch = min(int(cw * rng.uniform(0.75, 1.3)), h)
            cx, cy = rng.randint(0, w - cw), rng.randint(0, h - ch)
            margin = 0.06 * w                          # the disc radius is about 0.035 of the width
            inside = cx + margin < x0 < cx + cw - margin and cy + margin < y0 < cy + ch - margin
            outside = not (cx - margin < x0 < cx + cw + margin and cy - margin < y0 < cy + ch + margin)
            if inside or outside:
                (with_disc if inside else without_disc).append(quality.measures(img[cy:cy + ch, cx:cx + cw])["disc_score"])
    with_disc, without_disc = np.array(with_disc), np.array(without_disc)

    # 3. warning rate on whole photographs
    aptos_scores, aptos_labels = [], []
    for r in csv.DictReader(open(RESULTS / "splits.csv", encoding="utf-8")):
        aptos_scores.append(quality.measures(cv2.imread(str(APTOS / r["label"] / f"{r['id']}.png")))["disc_score"])
        aptos_labels.append(r["label"])
    aptos_scores, idrid_scores, aptos_labels = np.array(aptos_scores), np.array(scores_full_idrid), np.array(aptos_labels)

    L = ["# Stage 1: is the optic disc in the picture?", "",
         "Generated by `validation/disc_check.py` from the shipped gate (`backend/quality.py`, `disc_score`). It is a **warning**, never a rejection.", "",
         "## 1. Does the detector find the disc? (IDRiD, 516 photographs, disc centres marked by experts)", "",
         f"Distance between the detected blob and the marked disc centre, as a share of the retina width: within 0.05 for **{(err <= 0.05).mean() * 100:.1f}%**, "
         f"within 0.08 for {(err <= 0.08).mean() * 100:.1f}%; median {np.median(err):.3f}. (The disc radius is about 0.035.)", "",
         "## 2. Does its confidence separate frames with the disc from frames without? (frames cut from IDRiD photographs)", "",
         f"{len(with_disc)} frames with the disc fully inside, {len(without_disc)} with it clearly outside. AUC of the score: **{auc(with_disc, without_disc):.3f}**.", "",
         "| Group | n | 5th percentile | median | 95th percentile |", "|---|---|---|---|---|"]
    for name, v in (("Whole IDRiD photographs", idrid_scores), ("Whole APTOS photographs", aptos_scores), ("Frames with the disc", with_disc), ("Frames without the disc", without_disc)):
        L.append(f"| {name} | {len(v)} | {np.percentile(v, 5):.2f} | {np.median(v):.2f} | {np.percentile(v, 95):.2f} |")
    L += ["", f"## 3. The warning threshold ({THRESHOLD}) and what it costs", "",
          "| Threshold | Whole APTOS photos warned | Whole IDRiD photos warned | Frames without the disc caught | Frames with the disc wrongly warned |", "|---|---|---|---|---|"]
    for t in (2.0, 2.5, 3.0, 3.5, 4.0):
        mark = " (used)" if t == THRESHOLD else ""
        L.append(f"| {t}{mark} | {(aptos_scores < t).mean() * 100:.1f}% ({int((aptos_scores < t).sum())}) | {(idrid_scores < t).mean() * 100:.1f}% ({int((idrid_scores < t).sum())}) | "
                 f"{(without_disc < t).mean() * 100:.0f}% | {(with_disc < t).mean() * 100:.0f}% |")
    L += ["", f"## 4. Who gets the warning? (APTOS, threshold {THRESHOLD}, by disease grade)", "",
          "Looking at the lowest-scoring photographs, most do show a disc: it is pale or at the edge of a macula-centred photograph, or hidden by haze or fibrous tissue in advanced "
          "disease. So some warnings are false alarms, and they are a little more common in advanced disease.", "",
          "| Grade | Photos | Warned |", "|---|---|---|"]
    for g in ("No_DR", "Mild", "Moderate", "Severe", "Proliferate_DR"):
        m = aptos_labels == g
        L.append(f"| {g} | {int(m.sum())} | {int((aptos_scores[m] < THRESHOLD).sum())} ({(aptos_scores[m] < THRESHOLD).mean() * 100:.1f}%) |")
    L += ["", "## Limits", "",
          "- The detector is the brightest disc-sized blob. Bright lesions, glare or a bright rim can win instead, and a picture with no disc still has a brightest spot, "
          "so only a **low** score is informative. It does not prove the disc is present, and it does not check the macula.",
          "- Ground truth exists for IDRiD only. APTOS has no disc annotations, so for APTOS only the warning rate is known, not the accuracy.",
          "- The 'frames' are windows cut from complete photographs, not real photographs taken off-centre; real off-centre photographs also show a different rim and illumination.",
          "- A warning is advice to check the framing. The photograph is still graded.", ""]
    text = "\n".join(L)
    (RESULTS / "disc_check.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
