"""Stage 1 'is it a whole colour fundus photograph?' checks (backend/quality.py) against every real photograph we have, and against
non-fundus and partial pictures. Real photographs must (almost) never be rejected by the new rules; non-fundus pictures must be.

    python validation/fundus_check.py        # writes results/fundus_check.md (a few minutes)
"""
import csv
import sys
from collections import Counter
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "validation" / "results"
APTOS = ROOT / "data" / "aptos2019" / "colored_images"
IDRID = ROOT / "data" / "idrid_grading" / "B. Disease Grading" / "B. Disease Grading" / "1. Original Images"
sys.path.insert(0, str(ROOT / "backend"))
import quality  # noqa: E402

NEW = ("not_colour_reject", "partial_reject", "colour_warn")


def real_photos():
    for r in csv.DictReader(open(RESULTS / "splits.csv", encoding="utf-8")):
        yield "APTOS", r["id"], APTOS / r["label"] / f"{r['id']}.png"
    for r in csv.DictReader(open(RESULTS / "idrid_splits.csv", encoding="utf-8")):
        folder = "a. Training Set" if r["split"] == "train" else "b. Testing Set"
        yield "IDRiD", r["id"], IDRID / folder / f"{r['name']}.jpg"


def non_fundus():
    """Pictures that are not fundus photographs: real photos shipped with scikit-learn/matplotlib, plus simple synthetic ones."""
    from sklearn.datasets import load_sample_images
    import matplotlib.cbook as cbook

    out = {f"photo (scikit-learn #{i})": cv2.cvtColor(im, cv2.COLOR_RGB2BGR) for i, im in enumerate(load_sample_images().images)}
    for name in ("grace_hopper.jpg", "Minduka_Present_Blue_Pack.png"):
        with cbook.get_sample_data(name) as f:
            out[f"photo ({name})"] = cv2.imdecode(np.frombuffer(f.read(), np.uint8), cv2.IMREAD_COLOR)
    rng = np.random.default_rng(0)
    page = np.full((600, 800, 3), 235, np.uint8)
    for _ in range(300):
        cv2.putText(page, "abc def", (int(rng.integers(0, 700)), int(rng.integers(20, 580))), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 1)
    out["text page"] = page
    out["random noise"] = rng.integers(0, 255, (400, 400, 3), dtype=np.uint8)
    g = np.tile(np.linspace(0, 255, 800, dtype=np.uint8), (600, 1))
    out["grey gradient"] = cv2.merge([g, g, g])
    disc = np.zeros((600, 600, 3), np.uint8)
    cv2.circle(disc, (300, 300), 280, (170, 170, 170), -1)
    out["grey disc on black"] = disc
    blue = np.zeros((600, 600, 3), np.uint8)
    cv2.circle(blue, (300, 300), 280, (200, 120, 60), -1)
    out["blue disc on black"] = cv2.add(blue, (rng.random((600, 600, 3)) * 20).astype(np.uint8))
    return out


def partial_crops():
    """Partial views made from real photographs (one per grade), so the retina colour and texture are genuine."""
    rows = list(csv.DictReader(open(RESULTS / "splits.csv", encoding="utf-8")))
    rng = np.random.default_rng(3)
    picks = [rows[i] for i in rng.choice(len(rows), 60, replace=False)]
    kinds = {
        "left half": lambda f: f[:, : f.shape[1] // 2],
        "right third": lambda f: f[:, -f.shape[1] // 3:],
        "top half": lambda f: f[: f.shape[0] // 2],
        "bottom half": lambda f: f[f.shape[0] // 2:],
    }
    for r in picks:
        img = cv2.imread(str(APTOS / r["label"] / f"{r['id']}.png"))
        for k, fn in kinds.items():
            yield k, np.ascontiguousarray(fn(img))


def main():
    counts, by_new, examples = Counter(), Counter(), []
    for dataset, image_id, path in real_photos():
        v = quality.verdict(quality.measures(cv2.imread(str(path))))
        counts[(dataset, v["verdict"])] += 1
        for r in v["reasons"]:
            if r in NEW:
                by_new[(dataset, r)] += 1
                examples.append((dataset, image_id, r))
    totals = {d: sum(n for (dd, _), n in counts.items() if dd == d) for d in ("APTOS", "IDRiD")}

    lines = ["# Stage 1: is it a whole colour fundus photograph?", "",
             "Generated by `validation/fundus_check.py` from the shipped gate (`backend/quality.py`).", "",
             "## Real fundus photographs (must not be rejected by the new rules)", "",
             "| Set | Images | Rejected: not a colour photo | Rejected: partial retina | Warned: unusual colour |", "|---|---|---|---|---|"]
    for d in ("APTOS", "IDRiD"):
        lines.append(f"| {d} | {totals[d]} | {by_new[(d, 'not_colour_reject')]} | {by_new[(d, 'partial_reject')]} | {by_new[(d, 'colour_warn')]} |")
    lines += ["", "## Pictures that are NOT whole colour fundus photographs (should be rejected or warned)", "", "| Picture | Verdict | Reasons |", "|---|---|---|"]
    for name, img in non_fundus().items():
        v = quality.verdict(quality.measures(img))
        lines.append(f"| {name} | {v['verdict']} | {', '.join(v['reasons']) or '-'} |")
    lines += ["", "## Partial views cut from real photographs (should be rejected)", "", "| View | Images | Rejected as partial | Otherwise |", "|---|---|---|---|"]
    tally = {}
    for kind, img in partial_crops():
        v = quality.verdict(quality.measures(img))
        t = tally.setdefault(kind, [0, 0, Counter()])
        t[0] += 1
        t[1] += "partial_reject" in v["reasons"]
        if "partial_reject" not in v["reasons"]:
            t[2][v["verdict"]] += 1
    for kind, (n, hit, other) in tally.items():
        lines.append(f"| {kind} | {n} | {hit} | {dict(other) or '-'} |")
    lines += ["", "## Limits", "",
              "- A picture with a warm colour cast and a round outline can still pass. These checks look at colour and outline only; they do not detect the optic disc, macula or vessels.",
              "- A quarter of a retina, or a zoomed-in crop with no black border, looks like a whole photograph to these checks.",
              "- The non-fundus set is small (a handful of pictures); it shows the rules work, not how often unusual uploads slip through.", ""]
    text = "\n".join(lines)
    (RESULTS / "fundus_check.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
