"""Does the MATLAB Stage 1 gate (stage1_quality/assessFundusQuality.m) decide like the Python gate the app runs (backend/quality.py)?

    python validation/stage1_parity.py          # needs MATLAB (matlab.engine); about 5 minutes

Photographs: held-out APTOS test photos at full resolution, IDRiD's official grading test set, and controlled degradations of APTOS test
photos (the same recipes as degradation_experiment.py: blur, darken, brighten, noise, JPEG) plus cases the gate must reject outright
(greyscale, the left half of a retina, a non-fundus pattern). Every photo is written to a temporary PNG so both gates read identical pixels.

Writes results/stage1_parity.md and results/stage1_parity.csv.
"""
import csv
import sys
import tempfile
from collections import Counter
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "validation" / "results"
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT / "validation"))
import quality  # noqa: E402
from degradation_experiment import CONDITIONS  # noqa: E402

APTOS_FULL = ROOT / "data" / "aptos2019_full" / "train_images"
APTOS_224 = ROOT / "data" / "aptos2019" / "colored_images"
IDRID = ROOT / "data" / "idrid_grading" / "B. Disease Grading" / "B. Disease Grading" / "1. Original Images" / "b. Testing Set"
MEASURES = ["brightness", "lap_var_norm", "hf_ratio", "warm_share", "retina_aspect", "disc_score"]


def cases():
    rng = np.random.default_rng(5)
    test = [r for r in csv.DictReader(open(RESULTS / "splits.csv", encoding="utf-8")) if r["split"] == "test"]
    for r in rng.choice(test, 150, replace=False):
        yield "APTOS full resolution", r["id"], cv2.imread(str(APTOS_FULL / f"{r['id']}.png"))
    for p in sorted(IDRID.glob("*.jpg")):
        yield "IDRiD test", p.stem, cv2.imread(str(p))
    for r in rng.choice(test, 20, replace=False):
        img = cv2.imread(str(APTOS_224 / r["label"] / f"{r['id']}.png"))
        for name, _, _, fn in CONDITIONS[1:]:
            yield f"degraded: {name}", r["id"], fn(img)
        yield "must reject: greyscale", r["id"], cv2.cvtColor(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), cv2.COLOR_GRAY2BGR)
        yield "must reject: half a retina", r["id"], img[:, : img.shape[1] // 2].copy()
    for k in range(5):
        noise = np.random.default_rng(k).integers(0, 255, (400, 400, 3), dtype=np.uint8)
        yield "must reject: not a fundus photo", f"noise{k}", noise


def main():
    import matlab.engine

    eng = matlab.engine.start_matlab()
    eng.addpath(str(ROOT / "stage1_quality"), nargout=0)
    rows = []
    with tempfile.TemporaryDirectory() as tmp:
        for i, (group, ident, img) in enumerate(cases()):
            path = str(Path(tmp) / "img.png")
            cv2.imwrite(path, img)
            img = cv2.imread(path)
            m_py = quality.measures(img)
            v_py = quality.verdict(m_py)
            v_ml, _msg, reasons_ml, m_ml = eng.assessFundusQuality(path, nargout=4)
            reasons_ml = [str(r) for r in (reasons_ml if isinstance(reasons_ml, list) else [reasons_ml])] if reasons_ml else []
            row = {"group": group, "id": ident, "python": v_py["verdict"], "matlab": str(v_ml),
                   "python_reasons": " ".join(v_py["reasons"]), "matlab_reasons": " ".join(reasons_ml)}
            for k in MEASURES:
                row[f"py_{k}"] = m_py.get(k, float("nan"))
                row[f"ml_{k}"] = float(m_ml[k]) if k in m_ml else float("nan")
            rows.append(row)
            if i % 50 == 0:
                print(i, group, row["python"], row["matlab"], flush=True)
    eng.quit()

    with open(RESULTS / "stage1_parity.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    md = ["# Stage 1: MATLAB gate vs the Python gate the app runs", "",
          "Generated by `validation/stage1_parity.py`. `stage1_quality/assessFundusQuality.m` is a port of `backend/quality.py`: same measures, thresholds and "
          "messages. Both gates read the same PNG for every photograph. Small differences come from the image libraries (OpenCV vs MATLAB resizing and "
          "Gaussian filters) and matter only for photographs close to a threshold.", "",
          "| Photographs | n | Same verdict | Python verdicts (accept / warn / reject) | MATLAB verdicts |", "|---|---|---|---|---|"]
    groups = list(dict.fromkeys(r["group"] for r in rows))
    for g in groups:
        sel = [r for r in rows if r["group"] == g]
        same = sum(r["python"] == r["matlab"] for r in sel)
        cp, cm = Counter(r["python"] for r in sel), Counter(r["matlab"] for r in sel)
        md.append(f"| {g} | {len(sel)} | {same}/{len(sel)} ({same / len(sel):.0%}) | {cp['accept']} / {cp['warn']} / {cp['reject']} | {cm['accept']} / {cm['warn']} / {cm['reject']} |")
    same = sum(r["python"] == r["matlab"] for r in rows)
    reject_both = sum((r["python"] == "reject") == (r["matlab"] == "reject") for r in rows)
    md += ["", f"**Overall: the same verdict for {same} of {len(rows)} photographs ({same / len(rows):.1%}); "
           f"the same reject / not-reject decision for {reject_both} of {len(rows)} ({reject_both / len(rows):.1%}).**", "",
           "Agreement of the underlying measures (Pearson correlation, all photographs where both are defined):", "",
           "| Measure | Correlation | Median relative difference |", "|---|---|---|"]
    for k in MEASURES:
        a = np.array([r[f"py_{k}"] for r in rows], float)
        b = np.array([r[f"ml_{k}"] for r in rows], float)
        ok = np.isfinite(a) & np.isfinite(b)
        rel = np.median(np.abs(a[ok] - b[ok]) / np.maximum(np.abs(a[ok]), 1e-6))
        md.append(f"| {k} | {np.corrcoef(a[ok], b[ok])[0, 1]:.3f} | {rel:.1%} |")
    diff = [r for r in rows if r["python"] != r["matlab"]]
    if diff:
        md += ["", "Photographs where the verdicts differ:", "", "| Group | Photo | Python | MATLAB |", "|---|---|---|---|"]
        md += [f"| {r['group']} | {r['id']} | {r['python']} ({r['python_reasons']}) | {r['matlab']} ({r['matlab_reasons']}) |" for r in diff[:40]]
    (RESULTS / "stage1_parity.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(md))


if __name__ == "__main__":
    main()
