function T = vesselDriveEval()
% VESSELDRIVEEVAL  Stage 2 vessel segmentation (stage2_structure/vesselSegmentation.m, classical) against DRIVE's manual vessel maps.
%
% DRIVE here is the Kaggle mirror in data/drive/DRIVE, which has manual annotations (1st observer) for the 20 TRAINING photographs
% only. vesselSegmentation.m is unsupervised (nothing was tuned on DRIVE), so these 20 are a fair test of it. Metrics inside DRIVE's own
% field-of-view masks, the usual protocol: accuracy, sensitivity, specificity and Dice at the method's own threshold, and AUC of its
% vesselness map. Published figures are on DRIVE's 20 TEST photographs, so the comparison is indicative.
% If the trained vessel network exists (stage2_structure/dl/Stage2_VesselUNet.mat), its out-of-fold cross-validation metrics on
% the same 20 photos (stored in the model by trainVesselSegmenter) are added as a row: each photo was predicted by a network
% that never saw it.
% Writes validation/results/vessels_drive.md and .csv.
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root, 'stage2_structure'), fullfile(root, 'stage1_quality'), fullfile(root, 'utils'));
    base = fullfile(root, 'data', 'drive', 'DRIVE', 'training');
    files = dir(fullfile(base, 'images', '*.tif'));
    n = numel(files);
    T = table(strings(n, 1), zeros(n, 1), zeros(n, 1), zeros(n, 1), zeros(n, 1), zeros(n, 1), ...
        'VariableNames', {'image', 'accuracy', 'sensitivity', 'specificity', 'dice', 'auc'});
    for i = 1:n
        stem = erase(files(i).name, '_training.tif');
        img = imread(fullfile(files(i).folder, files(i).name));
        gt = imread(fullfile(base, '1st_manual', [stem '_manual1.gif'])) > 0;
        fov = imread(fullfile(base, 'mask', [stem '_training_mask.gif'])) > 0;
        r = vesselSegmentation(img, struct('visualize', false, 'verbose', false));
        p = r.vesselMask(fov); g = gt(fov); s = r.vesselProb(fov);
        tp = nnz(p & g); tn = nnz(~p & ~g); fp = nnz(p & ~g); fn = nnz(~p & g);
        T.image(i) = stem;
        T.accuracy(i) = (tp + tn) / numel(g);
        T.sensitivity(i) = tp / (tp + fn);
        T.specificity(i) = tn / (tn + fp);
        T.dice(i) = 2 * tp / (2 * tp + fp + fn);
        T.auc(i) = rocAuc(double(s), g);
    end
    writetable(T, fullfile(root, 'validation', 'results', 'vessels_drive.csv'));
    m = @(v) mean(v);
    dlRow = {}; dlNote = {};
    dlFile = fullfile(root, 'stage2_structure', 'dl', 'Stage2_VesselUNet.mat');
    if isfile(dlFile)
        S = load(dlFile, 'model'); cv = S.model.crossValidation;
        writetable(cv, fullfile(root, 'validation', 'results', 'vessels_drive_unet_cv.csv'));
        dlRow = {sprintf('| **This project: vessel U-Net (trained; %d-fold cross-validation, out-of-fold)** | %.4f | %.4f | %.4f | %.3f | %.4f |', ...
            max(cv.fold), m(cv.accuracy), m(cv.sensitivity), m(cv.specificity), m(cv.dice), m(cv.auc))};
        dlNote = {'', sprintf(['U-Net row: `stage2_structure/dl/trainVesselSegmenter.m`. Each photo is scored by a network trained on the ' ...
            'other %d folds, at that fold''s threshold (best Dice on its own training photos). The deployed network ' ...
            '(`Stage2_VesselUNet.mat`, applied with `segmentVesselsDL.m`) is trained on all 20 with threshold %.2f. Per photo: ' ...
            '`vessels_drive_unet_cv.csv`.'], max(cv.fold) - 1, S.model.threshold)};
    end
    lines = {'# Stage 2 vessels on DRIVE', '', ...
        sprintf(['Generated by `validation/vesselDriveEval.m`. %d DRIVE photographs with manual vessel maps (the training set of the Kaggle mirror; ' ...
        'the classical method is unsupervised and was not tuned on DRIVE). Mean over photographs, inside DRIVE''s field-of-view masks.'], n), '', ...
        '| Method | Accuracy | Sensitivity | Specificity | Dice | AUC |', '|---|---|---|---|---|---|', ...
        sprintf('| **This project: vesselSegmentation.m (unsupervised, Frangi-type)** | %.4f | %.4f | %.4f | %.3f | %.4f |', ...
            m(T.accuracy), m(T.sensitivity), m(T.specificity), m(T.dice), m(T.auc)), ...
        dlRow{:}, ...
        '| 2nd human observer (DRIVE test set) | 0.9464 | 0.7796 | 0.9717 | - | - |', ...
        '| Azzopardi et al., B-COSFIRE (unsupervised; test set) | 0.9442 | 0.7656 | 0.9704 | - | 0.9614 |', ...
        '| Soares et al. 2006 (supervised; test set) | 0.9461 | 0.7332 | 0.9782 | - | 0.9614 |', '', ...
        ['Published rows: Table 4 of Memari et al., "Supervised retinal vessel segmentation from color fundus images based on matched filtering ' ...
        'and AdaBoost classifier", PLOS ONE 2017 (https://pmc.ncbi.nlm.nih.gov/articles/PMC5724901/). They are on DRIVE''s test photographs; ' ...
        'this mirror has no test annotations, so the comparison is indicative.'], dlNote{:}};
    fid = fopen(fullfile(root, 'validation', 'results', 'vessels_drive.md'), 'w'); fprintf(fid, '%s\n', lines{:}); fclose(fid);
    fprintf('%s\n', lines{:});
end

function a = rocAuc(score, label)
    pos = score(label); neg = score(~label);
    r = tiedrank([pos; neg]);
    a = (sum(r(1:numel(pos))) - numel(pos) * (numel(pos) + 1) / 2) / (numel(pos) * numel(neg));
end
